[project]
name = "repl-nix-workspace"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "flask-cors==4.0.0",
    "flask==2.3.3",
    "numpy==1.24.3",
    "scikit-learn==1.3.0",
    "requests==2.31.0",
    "pandas==2.0.3",
]
